name: Bricologic
favicon: null
layout_spectrum: 0.9303261579480022
typography_spectrum: 0.7267014554236084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1d1d'
    - '#b6b1ab'
    - '#696b66'
    - '#0187e8'
  brandStrength: 0.6875
  lightness: 0.6901803074870259
  saturation: 0.5500858153682202
  rhythmicContrast: 0.792313804384321
purpose: []
